version: "3.8"

services:
  flux-setup:
    build:
      context: .
      dockerfile: Dockerfile
      image: ghcr.io/miike-ai/xulf:latest
    ports:
      - "7860:7860"
      - "8888:8888"
    environment:
      HF_HUB_ENABLE_HF_TRANSFER: "1"
      HF_HUB_DISABLE_SSL_VERIFY: "1"
    volumes:
      - workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  workspace:
    driver: local
